---
- name: Instala o Swarm Manager Principal
  become: yes
  hosts: d13-swarm-manager1

  vars:
    swarm_advertise_addr: "{{ ansible_host }}"

  tasks:

    - name: Aplica a Role fflch.tasks
      include_role:
        name: fflch.tasks
      vars:
        tasks_common: true

    - include_role:
        name: geerlingguy.docker

    - name: Verifica se o Host já participa de um Cluster Swarm
      command: docker info --format '{{ "{{" }} .Swarm.LocalNodeState {{ "}}" }}'
      register: swarm_status
      changed_when: false

    - name: Inicializa o Swarm
      command: >
        docker swarm init
        --advertise-addr {{ swarm_advertise_addr }}
      when: swarm_status.stdout != "active"

    - name: Obtem o Token de Manager
      command: docker swarm join-token -q manager
      register: manager_token
      changed_when: false

    - name: Obtem o Token de Worker
      command: docker swarm join-token -q worker
      register: worker_token
      changed_when: false

    - name: Salva o Token de Manager no Chaveiro
      shell: |
        echo "{{ manager_token.stdout }}" | \
        pass insert -f -m sti/tokens/swarm/manager
      become: false
      delegate_to: localhost

    - name: Salva o Token de Worker no Chaveiro
      shell: |
        echo "{{ worker_token.stdout }}" | \
        pass insert -f -m sti/tokens/swarm/worker
      become: false
      delegate_to: localhost 

    - name: Exibe o Token de Manager
      debug:
        msg: "{{ manager_token.stdout }}"

    - name: Exibe o Token de Worker
      debug:
        msg: "{{ worker_token.stdout }}"
