---
- name: d13-swarm-manager3
  become: yes
  hosts: d13-swarm-manager3


  #### tasks
  tasks:

    - name: Aplica role fflch.tasks 
      include_role:
        name: fflch.tasks
      vars:
        tasks_common: true

    - include_role:
        name: geerlingguy.docker